#pragma once

#define OFX_GGML_STABLE_DIFFUSION_VERSION_MAJOR 1
#define OFX_GGML_STABLE_DIFFUSION_VERSION_MINOR 0
#define OFX_GGML_STABLE_DIFFUSION_VERSION_PATCH 1
#define OFX_GGML_STABLE_DIFFUSION_VERSION "1.0.1"

static constexpr const char * OFX_GGML_STABLE_DIFFUSION_VERSION_STRING =
	OFX_GGML_STABLE_DIFFUSION_VERSION;
